/**
 * Docker Module - Docker integration helpers
 * Generates .env files, docker-compose templates, and manages containers
 */

const fs = require('fs-extra');
const path = require('path');
const { exec } = require('child_process');
const { promisify } = require('util');

const execAsync = promisify(exec);

/**
 * Generate Docker .env file for a project
 * @param {string} basePath - Project base path
 * @param {Object} config - Project configuration
 * @returns {Promise<string>} Path to created .env file
 */
async function generateDockerEnv(basePath, config) {
  const envPath = path.join(basePath, '.env');
  const envContent = `# Generated by Dev Port Manager
# ${new Date().toISOString()}
# 
# This file is automatically loaded by Docker Compose
# Do not commit to version control if it contains sensitive data

# Project Configuration
PROJECT_NAME=${config.name}
PROJECT_TYPE=${config.projectType || 'unknown'}

# Network Configuration
# PORT: The host port assigned by Dev Port Manager
# This port is mapped to the container's internal port (usually 8080)
PORT=${config.port}

# HOST: The localtest.me hostname for this project
HOST=${config.host}

# URL: Full access URL for the project
URL=${config.url}

# Docker Configuration
# CONTAINER_PORT: Internal port the application runs on inside the container
CONTAINER_PORT=8080

# Additional environment variables for your application
NODE_ENV=development
DEBUG=true
`;
  await fs.writeFile(envPath, envContent);
  return envPath;
}

/**
 * Generate Docker Compose override file for a project
 * @param {string} basePath - Project base path
 * @param {Object} config - Project configuration
 * @param {number} containerPort - Internal container port (default: 8080)
 * @returns {Promise<string>} Path to created docker-compose.override.yml
 */
async function generateDockerComposeOverride(basePath, config, containerPort = 8080) {
  const composePath = path.join(basePath, 'docker-compose.override.yml');
  const serviceName = (config.name || 'app').replace(/[^a-zA-Z0-9]/g, '-');
  
  const composeContent = `version: '3.8'

# Docker Compose Override for ${config.name || 'app'}
# Generated by Dev Port Manager
# 
# Usage:
#   docker-compose up -d
#   docker-compose down
#
# This file overrides docker-compose.yml settings for local development

services:
  ${serviceName}:
    ports:
      # Maps host port (from .env) to container port
      - "\${PORT:-${config.port}}:${containerPort}"
    environment:
      # Override environment for development
      - NODE_ENV=development
      - DEBUG=true
      - PORT=${containerPort}
    volumes:
      # Mount local directory for hot reload
      - .:/app
      # Prevent node_modules from being overwritten (Node.js only)
      - /app/node_modules
    build:
      context: .
      target: development
    restart: unless-stopped
`;
  await fs.writeFile(composePath, composeContent);
  return composePath;
}

/**
 * Check if Docker is available
 * @returns {Promise<boolean>} True if Docker is available
 */
async function isDockerAvailable() {
  try {
    await execAsync('docker --version');
    return true;
  } catch (err) {
    return false;
  }
}

/**
 * Check if Docker Compose is available
 * @returns {Promise<boolean>} True if Docker Compose is available
 */
async function isDockerComposeAvailable() {
  try {
    await execAsync('docker-compose --version');
    return true;
  } catch (err) {
    try {
      // Docker Compose V2 uses 'docker compose' (without hyphen)
      await execAsync('docker compose version');
      return true;
    } catch (err2) {
      return false;
    }
  }
}

/**
 * Get Docker Compose command (handles v1 and v2)
 * @returns {string} Docker Compose command
 */
function getDockerComposeCommand() {
  // Try V2 first, then V1
  try {
    execSync('docker compose version', { stdio: 'ignore' });
    return 'docker compose';
  } catch (err) {
    return 'docker-compose';
  }
}

/**
 * Start Docker Compose services
 * @param {string} basePath - Project base path
 * @returns {Promise<Object>} Result with output
 */
async function startDockerServices(basePath) {
  const composeCmd = getDockerComposeCommand();
  try {
    const { stdout, stderr } = await execAsync(`${composeCmd} up -d`, {
      cwd: basePath,
      env: process.env
    });
    return {
      success: true,
      output: stdout,
      error: stderr
    };
  } catch (err) {
    return {
      success: false,
      error: err.message
    };
  }
}

/**
 * Stop Docker Compose services
 * @param {string} basePath - Project base path
 * @returns {Promise<Object>} Result with output
 */
async function stopDockerServices(basePath) {
  const composeCmd = getDockerComposeCommand();
  try {
    const { stdout, stderr } = await execAsync(`${composeCmd} down`, {
      cwd: basePath,
      env: process.env
    });
    return {
      success: true,
      output: stdout,
      error: stderr
    };
  } catch (err) {
    return {
      success: false,
      error: err.message
    };
  }
}

/**
 * Restart Docker Compose services
 * @param {string} basePath - Project base path
 * @returns {Promise<Object>} Result with output
 */
async function restartDockerServices(basePath) {
  const composeCmd = getDockerComposeCommand();
  try {
    const { stdout, stderr } = await execAsync(`${composeCmd} restart`, {
      cwd: basePath,
      env: process.env
    });
    return {
      success: true,
      output: stdout,
      error: stderr
    };
  } catch (err) {
    return {
      success: false,
      error: err.message
    };
  }
}

/**
 * Get Docker Compose services status
 * @param {string} basePath - Project base path
 * @returns {Promise<Object>} Status with running services
 */
async function getDockerServicesStatus(basePath) {
  const composeCmd = getDockerComposeCommand();
  try {
    const { stdout } = await execAsync(`${composeCmd} ps --format json`, {
      cwd: basePath,
      env: process.env
    });
    
    const services = JSON.parse(stdout);
    return {
      success: true,
      services,
      running: services.filter(s => s.State === 'running').length
    };
  } catch (err) {
    return {
      success: false,
      error: err.message,
      running: 0
    };
  }
}

/**
 * Get Docker container logs
 * @param {string} basePath - Project base path
 * @param {string} serviceName - Service name
 * @returns {Promise<Object>} Logs output
 */
async function getDockerLogs(basePath, serviceName) {
  try {
    const { stdout } = await execAsync(`docker logs ${serviceName}`, {
      cwd: basePath,
      env: process.env,
      maxBuffer: 1024 * 1024 // 1MB buffer
    });
    return {
      success: true,
      logs: stdout
    };
  } catch (err) {
    return {
      success: false,
      error: err.message
    };
  }
}

/**
 * Check if a project has Docker files
 * @param {string} basePath - Project base path
 * @returns {Promise<Object>} Docker file detection result
 */
async function hasDockerFiles(basePath) {
  const dockerfile = path.join(basePath, 'Dockerfile');
  const dockerCompose = path.join(basePath, 'docker-compose.yml');
  const dockerComposeOverride = path.join(basePath, 'docker-compose.override.yml');
  const dockerEnv = path.join(basePath, '.env');
  
  return {
    hasDockerfile: await fs.pathExists(dockerfile),
    hasDockerCompose: await fs.pathExists(dockerCompose),
    hasDockerComposeOverride: await fs.pathExists(dockerComposeOverride),
    hasDockerEnv: await fs.pathExists(dockerEnv)
  };
}

module.exports = {
  generateDockerEnv,
  generateDockerComposeOverride,
  isDockerAvailable,
  isDockerComposeAvailable,
  getDockerComposeCommand,
  startDockerServices,
  stopDockerServices,
  restartDockerServices,
  getDockerServicesStatus,
  getDockerLogs,
  hasDockerFiles
};
