const fs = require('fs').promises;
const path = require('path');
const os = require('os');

class HostsManager {
  constructor() {
    this.isWindows = os.platform() === 'win32';
    this.hostsPath = this.isWindows
      ? 'C:\\Windows\\System32\\drivers\\etc\\hosts'
      : '/etc/hosts';
    this.markerStart = '# === DEV PORT MANAGER START ===';
    this.markerEnd = '# === DEV PORT MANAGER END ===';
  }

  async backup() {
    try {
      const content = await fs.readFile(this.hostsPath, 'utf-8');
      const backupPath = `${this.hostsPath}.dpm.backup.${Date.now()}`;
      await fs.writeFile(backupPath, content, 'utf-8');
      return backupPath;
    } catch (error) {
      throw new Error(`Failed to backup hosts file: ${error.message}`);
    }
  }

  async readHosts() {
    try {
      const content = await fs.readFile(this.hostsPath, 'utf-8');
      return content;
    } catch (error) {
      throw new Error(`Failed to read hosts file: ${error.message}`);
    }
  }

  async updateHosts(entries, removeStale = true) {
    try {
      let content = await this.readHosts();

      // Remove existing DPM entries
      const startIdx = content.indexOf(this.markerStart);
      const endIdx = content.indexOf(this.markerEnd);

      if (startIdx !== -1 && endIdx !== -1) {
        content = content.substring(0, startIdx) + content.substring(endIdx + this.markerEnd.length);
      }

      // Generate new entries
      let dpmBlock = `\n${this.markerStart}\n`;
      dpmBlock += '# Auto-generated by Dev Port Manager\n';
      dpmBlock += `# Updated: ${new Date().toISOString()}\n`;

      for (const entry of entries) {
        dpmBlock += `127.0.0.1 ${entry.host} # ${entry.project} (port ${entry.port})\n`;
      }

      dpmBlock += `${this.markerEnd}\n`;

      content += dpmBlock;

      await fs.writeFile(this.hostsPath, content, 'utf-8');
    } catch (error) {
      if (error.code === 'EACCES') {
        throw new Error('Permission denied. Run with sudo/admin privileges to update /etc/hosts');
      }
      throw error;
    }
  }

  async removeAllDPMEntries() {
    try {
      let content = await this.readHosts();

      const startIdx = content.indexOf(this.markerStart);
      const endIdx = content.indexOf(this.markerEnd);

      if (startIdx !== -1 && endIdx !== -1) {
        content = content.substring(0, startIdx) + content.substring(endIdx + this.markerEnd.length);
        await fs.writeFile(this.hostsPath, content, 'utf-8');
      }
    } catch (error) {
      throw new Error(`Failed to remove DPM entries: ${error.message}`);
    }
  }

  async verifyEntry(host) {
    try {
      const content = await this.readHosts();
      const regex = new RegExp(`^127\\.0\\.0\\.1\\s+${host}\s*(?:#.*)?$`, 'm');
      return regex.test(content);
    } catch (error) {
      return false;
    }
  }

  getHostsPath() {
    return this.hostsPath;
  }

  isSupported() {
    // /etc/hosts management is supported on Unix-like systems and Windows
    // For Docker containers or special environments, may need alternative approach
    return true;
  }

  getAlternativeApproach() {
    return {
      method: 'localtest.me',
      description: 'Use *.localtest.me wildcard (no admin needed)',
      example: 'myproject.localtest.me resolves to 127.0.0.1 automatically'
    };
  }
}

module.exports = HostsManager;
