/**
 * Project Module - Core project management logic
 * Handles port assignment, project detection, and configuration generation
 * Cross-platform: Works on Windows, macOS, and Linux
 */

const { readRegistry, writeRegistry, REGISTRY_FILE, REGISTRY_DIR } = require('./registry');
const settings = require('./settings');
const hostUtils = require('./host');
const fs = require('fs-extra');
const path = require('path');
const os = require('os');
const net = require('net');

// Port range configuration (from settings or defaults)
function getPortRange() {
  const range = settings.getPortRange();
  return { BASE_PORT: range[0], MAX_PORT: range[1] };
}

/**
 * Check if a port is available (not in use by another process)
 * @param {number} port - Port number to check
 * @returns {Promise<boolean>} True if port is available
 */
async function isPortAvailable(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', (err) => {
      if (err.code === 'EADDRINUSE') {
        resolve(false);
      } else {
        resolve(false);
      }
    });
    server.once('listening', () => {
      server.close(() => resolve(true));
    });
    server.listen(port, '127.0.0.1');
  });
}

/**
 * Detect project type based on files present in the project directory
 * @param {string} projectPath - Path to project directory
 * @returns {string} Project type identifier
 */
function detectProjectType(projectPath) {
  if (!fs.existsSync(projectPath)) return 'unknown';
  
  // Java projects
  if (fs.existsSync(path.join(projectPath, 'pom.xml'))) return 'maven';
  if (fs.existsSync(path.join(projectPath, 'build.gradle')) || 
      fs.existsSync(path.join(projectPath, 'build.gradle.kts'))) return 'gradle';
  
  // Node.js projects
  if (fs.existsSync(path.join(projectPath, 'package.json'))) return 'node';
  
  // Python projects
  if (fs.existsSync(path.join(projectPath, 'requirements.txt')) ||
      fs.existsSync(path.join(projectPath, 'setup.py')) ||
      fs.existsSync(path.join(projectPath, 'pyproject.toml'))) return 'python';
  
  // Ruby projects
  if (fs.existsSync(path.join(projectPath, 'Gemfile'))) return 'ruby';
  
  // Rust projects
  if (fs.existsSync(path.join(projectPath, 'Cargo.toml'))) return 'rust';
  
  // Go projects
  if (fs.existsSync(path.join(projectPath, 'go.mod'))) return 'go';
  
  // PHP projects
  if (fs.existsSync(path.join(projectPath, 'composer.json'))) return 'php';
  
  // Manual marker
  if (fs.existsSync(path.join(projectPath, '.project-marker'))) return 'marked';
  
  return 'other';
}

/**
 * Generate Docker .env file for a project
 * @param {string} basePath - Project base path
 * @param {Object} config - Project configuration
 * @returns {Promise<string>} Path to created .env file
 */
async function generateDockerEnv(basePath, config) {
  const envPath = path.join(basePath, '.env');
  const envContent = `# Generated by Dev Port Manager
# ${new Date().toISOString()}

PORT=${config.port}
HOST=${config.host}
URL=${config.url}
PROJECT_NAME=${config.name}
PROJECT_TYPE=${config.projectType || 'unknown'}
`;
  await fs.writeFile(envPath, envContent);
  return envPath;
}

/**
 * Generate Docker Compose template for a project
 * @param {string} basePath - Project base path
 * @param {Object} config - Project configuration
 * @param {number} containerPort - Internal container port (default: 8080)
 * @returns {Promise<string>} Path to created docker-compose.yml
 */
async function generateDockerCompose(basePath, config, containerPort = 8080) {
  const composePath = path.join(basePath, 'docker-compose.yml');
  const composeContent = `version: '3.8'

services:
  ${config.name.replace(/[^a-zA-Z0-9]/g, '-')}:
    build: .
    ports:
      - "\${PORT:-${config.port}}:${containerPort}"
    environment:
      - PORT=${containerPort}
      - NODE_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
`;
  await fs.writeFile(composePath, composeContent);
  return composePath;
}

/**
 * Assign a port and host to a project
 * @param {string} projectName - Name of the project
 * @param {Object} options - Optional configuration
 * @param {number} options.port - Specific port to assign (optional)
 * @param {string} options.host - Custom host (optional)
 * @param {string} options.basePath - Base path for project files (default: process.cwd())
 * @param {boolean} options.checkPort - Check if port is actually available (default: true)
 * @param {boolean} options.generateDocker - Generate Docker .env file (default: false)
 * @returns {Promise<Object>} Project info with name, host, port, url, and metadata
 */
async function assignProject(projectName, options = {}) {
  const {
    port: customPort,
    host: customHost,
    basePath = process.cwd(),
    checkPort = true,
    generateDocker = false
  } = options;

  const { BASE_PORT, MAX_PORT } = getPortRange();
  const registry = await readRegistry();
  const usedPorts = Object.values(registry).map(p => p.port);

  let port;
  if (customPort) {
    if (usedPorts.includes(customPort)) {
      throw new Error(`Port ${customPort} is already in use by another project`);
    }
    if (checkPort && !await isPortAvailable(customPort)) {
      throw new Error(`Port ${customPort} is currently in use by another process`);
    }
    port = customPort;
  } else {
    port = BASE_PORT;
    while (usedPorts.includes(port) || (checkPort && !await isPortAvailable(port))) {
      port++;
    }
  }

  if (port > MAX_PORT) {
    throw new Error(`No available ports in range ${BASE_PORT}–${MAX_PORT}`);
  }

  const host = customHost || `${projectName}.localtest.me`;
  const url = `http://${host}:${port}`;
  const localhostUrl = `http://localhost:${port}`;
  const projectType = detectProjectType(basePath);
  const platform = os.platform();
  const timestamp = new Date().toISOString();
  
  // Update registry
  registry[projectName] = { 
    port, 
    host, 
    url,
    localhostUrl,  // Always include localhost URL
    projectType,
    os: platform,
    assignedAt: timestamp,
    updatedAt: timestamp,
    basePath  // Store basePath for easy access
  };
  await writeRegistry(registry);

  // Create per-project config
  const projectFile = path.join(basePath, '.project-dev.json');
  const projectConfig = { 
    name: projectName, 
    host, 
    port, 
    url,
    projectType,
    os: platform,
    assignedAt: timestamp,
    basePath
  };
  await fs.writeJson(projectFile, projectConfig, { spaces: 2 });

  // Create VS Code settings
  const vscodeDir = path.join(basePath, '.vscode');
  await fs.ensureDir(vscodeDir);
  await fs.writeJson(path.join(vscodeDir, 'settings.json'), { 
    'dev.port': port, 
    'dev.host': host,
    'dev.url': url
  }, { spaces: 2 });

  // Optionally generate Docker files
  if (generateDocker) {
    await generateDockerEnv(basePath, projectConfig);
  }

  return { 
    name: projectName, 
    host, 
    port, 
    url, 
    projectType, 
    os: platform,
    basePath 
  };
}

/**
 * List all registered projects
 * @returns {Object} Registry data
 */
function listProjects() {
  const registry = fs.readJsonSync(REGISTRY_FILE);
  return registry;
}

/**
 * Remove a project from the registry
 * @param {string} projectName - Name of the project to remove
 * @returns {Promise<boolean>} True if removed, false if not found
 */
async function removeProject(projectName) {
  const registry = await readRegistry();
  if (registry[projectName]) {
    delete registry[projectName];
    await writeRegistry(registry);
    return true;
  }
  return false;
}

/**
 * Get project info by name
 * @param {string} projectName - Name of the project
 * @returns {Object|null} Project info or null if not found
 */
function getProject(projectName) {
  const registry = fs.readJsonSync(REGISTRY_FILE);
  return registry[projectName] || null;
}

/**
 * Get all projects as an array with basePath from .project-dev.json
 * @returns {Array} Array of project objects with name and info
 */
function getAllProjects() {
  const registry = fs.readJsonSync(REGISTRY_FILE);
  let registryUpdated = false;
  
  const projects = Object.entries(registry).map(([name, info]) => {
    // Try to get basePath from .project-dev.json if not in registry
    let basePath = info.basePath;
    
    if (!basePath) {
      // First, try to find .project-dev.json in registry
      const possiblePaths = [
        path.join(os.homedir(), 'Projects', name, '.project-dev.json'),
        path.join(os.homedir(), 'projects', name, '.project-dev.json'),
        path.join(os.homedir(), 'dev', name, '.project-dev.json'),
        path.join(os.homedir(), 'src', name, '.project-dev.json'),
        path.join(os.homedir(), name, '.project-dev.json')
      ];
      
      for (const projPath of possiblePaths) {
        if (fs.existsSync(projPath)) {
          try {
            const projConfig = fs.readJsonSync(projPath);
            if (projConfig.basePath) {
              basePath = projConfig.basePath;
              info.basePath = basePath;
              registryUpdated = true;
              break;
            }
          } catch (err) {
            // Ignore errors
          }
        }
      }
    }
    
    return {
      name,
      ...info,
      basePath: basePath || 'N/A'
    };
  });
  
  // Save registry updates
  if (registryUpdated) {
    writeRegistrySync(registry);
  }
  
  return projects;
}

/**
 * Sync hosts - with localtest.me this is a no-op by default
 * Can optionally edit the hosts file for custom domains
 * @param {Object} options - Sync options
 * @param {boolean} options.useHostsFile - Edit hosts file instead of using localtest.me
 * @returns {Promise<Object>} Sync result
 */
async function syncHosts(options = {}) {
  const { useHostsFile = false } = options;
  
  if (!useHostsFile) {
    // Using localtest.me wildcard DNS, no need to edit hosts file
    return { 
      success: true, 
      message: 'Using *.localtest.me wildcard DNS, no hosts file changes needed',
      hostsFile: null
    };
  }
  
  // Edit hosts file
  const registry = await readRegistry();
  
  if (!hostUtils.isElevated()) {
    return {
      success: false,
      message: `Elevated privileges required: ${hostUtils.getElevationWarning()}`,
      hostsFile: hostUtils.getHostsFilePath()
    };
  }
  
  try {
    const result = await hostUtils.syncHostsFile(registry);
    return {
      success: true,
      message: `Synced ${result.entries} entries to hosts file`,
      hostsFile: result.hostsFile,
      entries: result.entries
    };
  } catch (err) {
    return {
      success: false,
      message: err.message,
      hostsFile: hostUtils.getHostsFilePath()
    };
  }
}

/**
 * Scan a base directory and auto-assign ports to unassigned projects
 * Detects: Maven, Gradle, Node.js, Python, Ruby, Rust, Go, PHP
 * Also respects .project-marker for manual override
 * @param {string} baseDir - Base directory to scan
 * @param {Object} options - Scan options
 * @param {boolean} options.dryRun - If true, only report what would be done
 * @param {boolean} options.generateDocker - Generate Docker .env files
 * @returns {Promise<Object>} Object with results, skipped, and errors arrays
 */
async function scanDirectory(baseDir, options = {}) {
  const { dryRun = false, generateDocker = false } = options;
  
  const resolvedBaseDir = path.resolve(baseDir);
  
  if (!await fs.pathExists(resolvedBaseDir)) {
    throw new Error(`Directory not found: ${resolvedBaseDir}`);
  }
  
  const folders = await fs.readdir(resolvedBaseDir);
  const results = [];
  const skipped = [];
  const errors = [];

  for (const folder of folders) {
    const fullPath = path.join(resolvedBaseDir, folder);
    const projectFile = path.join(fullPath, '.project-dev.json');

    try {
      const stats = await fs.stat(fullPath);
      if (!stats.isDirectory()) continue;
      
      // Skip already assigned projects
      if (await fs.pathExists(projectFile)) {
        skipped.push({ name: folder, reason: 'already assigned' });
        continue;
      }

      // Detect project type
      const projectType = detectProjectType(fullPath);
      const isProject = projectType !== 'other';
      
      if (!isProject) {
        skipped.push({ name: folder, reason: 'not a recognized project' });
        continue;
      }

      if (dryRun) {
        results.push({ name: folder, type: projectType, status: 'would be assigned' });
      } else {
        const info = await assignProject(folder, { basePath: fullPath, generateDocker });
        results.push({ ...info, type: projectType, status: 'assigned' });
      }
    } catch (err) {
      errors.push({ name: folder, error: err.message });
    }
  }

  return { results, skipped, errors };
}

/**
 * Scan a base directory recursively for projects
 * @param {string} baseDir - Base directory to scan
 * @param {number} maxDepth - Maximum recursion depth
 * @returns {Promise<Array>} Array of found project paths with types
 */
async function scanDirectoryRecursive(baseDir, maxDepth = 2) {
  const resolvedBaseDir = path.resolve(baseDir);
  const projects = [];

  async function scan(dir, depth) {
    if (depth > maxDepth) return;
    
    const items = await fs.readdir(dir);
    for (const item of items) {
      if (item.startsWith('.') || item === 'node_modules') continue;
      
      const fullPath = path.join(dir, item);
      try {
        const stats = await fs.stat(fullPath);
        if (stats.isDirectory()) {
          const projectType = detectProjectType(fullPath);
          if (projectType !== 'other') {
            projects.push({ path: fullPath, type: projectType });
          } else {
            await scan(fullPath, depth + 1);
          }
        }
      } catch (err) {
        // Skip inaccessible items
      }
    }
  }

  await scan(resolvedBaseDir, 0);
  return projects;
}

/**
 * Export registry to a file
 * @param {string} outputPath - Path to export to
 * @returns {Promise<string>} Path to exported file
 */
async function exportRegistry(outputPath) {
  const registry = await readRegistry();
  await fs.writeJson(outputPath, registry, { spaces: 2 });
  return outputPath;
}

/**
 * Import registry from a file
 * @param {string} inputPath - Path to import from
 * @param {boolean} merge - Whether to merge with existing registry (default: false)
 * @returns {Promise<Object>} Imported registry data
 */
async function importRegistry(inputPath, merge = false) {
  const importData = await fs.readJson(inputPath);
  
  if (!merge) {
    await writeRegistry(importData);
  } else {
    const existing = await readRegistry();
    const merged = { ...existing, ...importData };
    await writeRegistry(merged);
  }
  
  return importData;
}

/**
 * Create backup of registry with timestamp
 * @returns {Promise<string>} Path to backup file
 */
async function backupRegistry() {
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, -5);
  const backupPath = path.join(REGISTRY_DIR, `registry-backup-${timestamp}.json`);
  await exportRegistry(backupPath);
  return backupPath;
}

/**
 * Restore registry from a backup file
 * @param {string} backupPath - Path to backup file
 * @returns {Promise<Object>} Restored registry data
 */
async function restoreRegistry(backupPath) {
  return importRegistry(backupPath, false);
}

/**
 * List all registry backups
 * @returns {Promise<Array>} Array of backup file info
 */
async function listBackups() {
  const files = await fs.readdir(REGISTRY_DIR);
  const backups = files
    .filter(f => f.startsWith('registry-backup-') && f.endsWith('.json'))
    .map(f => ({
      filename: f,
      path: path.join(REGISTRY_DIR, f),
      timestamp: f.match(/registry-backup-(.+)\.json/)[1]
    }))
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp));
  return backups;
}

/**
 * Get the latest backup
 * @returns {Promise<Object|null>} Latest backup info or null
 */
async function getLatestBackup() {
  const backups = await listBackups();
  return backups.length > 0 ? backups[0] : null;
}

module.exports = {
  assignProject,
  listProjects,
  getAllProjects,
  removeProject,
  getProject,
  syncHosts,
  exportRegistry,
  importRegistry,
  backupRegistry,
  restoreRegistry,
  listBackups,
  getLatestBackup,
  scanDirectory,
  scanDirectoryRecursive,
  isPortAvailable,
  detectProjectType,
  generateDockerEnv,
  generateDockerCompose,
  getPortRange,
  REGISTRY_DIR,
  REGISTRY_FILE
};
